package com.lee.film.mapper;


import com.lee.film.model.*;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     *
     */

    User selectBycode(String code);




    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    User selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Mar 13 08:58:55 CST 2019
     */
    int updateByPrimaryKey(User record);

    User selectByUsername(String username);

    void updateByusername(User user);

    int finduser(String username);

    void updatepw(String username, String password);

    void updateinfo(User user);

//    Users finduserByusername(String username);
//
//    void insertuser(Users user);

    String checkemail(String username);

    void insertcode(String s, String code);

    int checkcode(String s, String ecode);

    void updatask(User user);

    void updaistask(User user);

    void updamytake(User user);

    List<Film> findfilm();

    List<OrdersEX> findOrder(String id);
}